name: Automated Linting

#Trigger: Run this whenever someone pushes code or opens a pull request
on: [push, pull_request]

jobs:
  check-code-quality:
    runs-on: ubuntu-latest    #Use a virtual Ubuntu Linux computer provided by GitHub

    defaults:    #Tell Github's virtual computer to cd into the assignment folder first
      run:
        working-directory: ./COP4331C_POOSD/Assignment1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6    #Copy the code onto the virtual computer

      - name: Setup Node.js
        uses: actions/setup-node@v6    #Install Node.js
        with:
            node-version: '22'    #Version 20 is reaching its end of life as of April 2026

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint    #Run the 'lint' shortcut in package.scripts.json
